export const TABLE_TO = {
    TITLE: [
        { TITLE: 'Автомобильный шиномонтаж' },
        { TITLE: '"ДЕМОНТАЖ-МОНТАЖ-БАЛАНСИРОВКА" ' },
        { TITLE: 'Железные диски' },
    ],
    COLUMN_ONE: [
        { TITLE: 'Радиус' },
        { CONTENT: 'R12', id: 1 },
        { CONTENT: 'R13', id: 2 },
        { CONTENT: 'R14', id: 3 },
        { CONTENT: 'R15', id: 4 },
        { CONTENT: 'R16', id: 5 },
        { CONTENT: 'R17', id: 6 },
        { CONTENT: 'R18', id: 7 },
    ],
    COLUMN_TO: [
        { TITLE: 'Демонтаж' },
        { CONTENT: '100', id: 1 },
        { CONTENT: '100', id: 2 },
        { CONTENT: '110', id: 3 },
        { CONTENT: '120', id: 4 },
        { CONTENT: '130', id: 5 },
        { CONTENT: '150', id: 6 },
        { CONTENT: '160', id: 7 },
    ],
    COLUMN_THREE: [
        { TITLE: 'Монтаж' },
        { CONTENT: '100', id: 1 },
        { CONTENT: '100', id: 2 },
        { CONTENT: '110', id: 3 },
        { CONTENT: '120', id: 4 },
        { CONTENT: '130', id: 5 },
        { CONTENT: '150', id: 6 },
        { CONTENT: '160', id: 7 },
    ],
    COLUMN_FOUR: [
        { TITLE: 'Балансировка' },
        { CONTENT: '100', id: 1 },
        { CONTENT: '100', id: 2 },
        { CONTENT: '110', id: 3 },
        { CONTENT: '120', id: 4 },
        { CONTENT: '130', id: 5 },
        { CONTENT: '150', id: 6 },
        { CONTENT: '160', id: 7 },
    ],
    COLUMN_FIVE: [
        { TITLE: 'за 4 колеса' },
        { CONTENT: '1200', id: 1 },
        { CONTENT: '1200', id: 2 },
        { CONTENT: '1320', id: 3 },
        { CONTENT: '1440', id: 4 },
        { CONTENT: '1560', id: 5 },
        { CONTENT: '1800', id: 6 },
        { CONTENT: '1920', id: 7 },
    ]
}

