export const TABLE_ONE = {
    TITLE: [
        { TITLE: 'Автомобильный шиномонтаж: ' },
        { TITLE: '"ДЕМОНТАЖ-МОНТАЖ-БАЛАНСИРОВКА"' },
    ],
    COLUMN_ONE: [
        { TITLE: 'Радиус' },
        { CONTENT: 'R12', id: 1 },
        { CONTENT: 'R13', id: 2 },
        { CONTENT: 'R14', id: 3 },
        { CONTENT: 'R15', id: 4 },
        { CONTENT: 'R16', id: 5 },
        { CONTENT: 'R17', id: 6 },
        { CONTENT: 'R18', id: 7 },
        { CONTENT: 'R19', id: 8 },
        { CONTENT: 'R20', id: 9 },
        { CONTENT: 'R21', id: 10 },
        { CONTENT: 'R22', id: 1 },
    ],
    COLUMN_TO: [
        { TITLE: 'Демонтаж' },
        { CONTENT: '110', id: 1 },
        { CONTENT: '110', id: 2 },
        { CONTENT: '120', id: 3 },
        { CONTENT: '130', id: 4 },
        { CONTENT: '140', id: 5 },
        { CONTENT: '160', id: 6 },
        { CONTENT: '170', id: 7 },
        { CONTENT: '190', id: 8 },
        { CONTENT: '260', id: 9 },
        { CONTENT: '260', id: 10 },
        { CONTENT: '260', id: 11 },
    ],
    COLUMN_THREE: [
        { TITLE: 'Монтаж' },
        { CONTENT: '110', id: 1 },
        { CONTENT: '110', id: 2 },
        { CONTENT: '120', id: 3 },
        { CONTENT: '130', id: 4 },
        { CONTENT: '140', id: 5 },
        { CONTENT: '160', id: 6 },
        { CONTENT: '170', id: 7 },
        { CONTENT: '190', id: 8 },
        { CONTENT: '260', id: 9 },
        { CONTENT: '260', id: 10 },
        { CONTENT: '260', id: 1 },
    ],
    COLUMN_FOUR: [
        { TITLE: 'Балансировка' },
        { CONTENT: '110', id: 1 },
        { CONTENT: '110', id: 2 },
        { CONTENT: '120', id: 3 },
        { CONTENT: '130', id: 4 },
        { CONTENT: '140', id: 5 },
        { CONTENT: '160', id: 6 },
        { CONTENT: '170', id: 7 },
        { CONTENT: '190', id: 8 },
        { CONTENT: '260', id: 9 },
        { CONTENT: '260', id: 10 },
        { CONTENT: '260', id: 11 },
    ],
    COLUMN_FIVE: [
        { TITLE: 'за 4 колеса' },
        { CONTENT: '1320', id: 1 },
        { CONTENT: '1320', id: 2 },
        { CONTENT: '1440', id: 3 },
        { CONTENT: '1560', id: 4 },
        { CONTENT: '1680', id: 5 },
        { CONTENT: '1920', id: 6 },
        { CONTENT: '2040', id: 7 },
        { CONTENT: '2280', id: 8 },
        { CONTENT: '3120', id: 9 },
        { CONTENT: '3120', id: 10 },
        { CONTENT: '3120', id: 11 },
    ]
}

